#!/usr/bin/env bash
# update-wasm-checksums.sh
#
# Rebuilds all WASM artifacts and updates wasm/checksums.sha256 with fresh
# SHA256 hashes. Run this locally whenever contract source changes and commit
# the updated checksums file alongside your code change.
#
# Usage: bash script/update-wasm-checksums.sh [--dry-run]
#
# Options:
#   --dry-run   Print what would be written without modifying checksums.sha256
#
# Exit codes:
#   0  Success — checksums file updated (or dry-run printed)
#   1  Build failed or WASM artifact missing

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECKSUMS_FILE="${REPO_ROOT}/wasm/checksums.sha256"
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Contracts to hash: name → relative WASM path from repo root
# Add new contracts here when they are added to the workspace.
# ---------------------------------------------------------------------------
declare -A CONTRACTS
CONTRACTS["fluxora_stream"]="target/wasm32-unknown-unknown/release/fluxora_stream.wasm"
CONTRACTS["fluxora_factory"]="target/wasm32-unknown-unknown/release/fluxora_factory.wasm"
CONTRACTS["fluxora_governance"]="target/wasm32-unknown-unknown/release/fluxora_governance.wasm"

# ---------------------------------------------------------------------------
# Verify required tools
# ---------------------------------------------------------------------------
for tool in cargo sha256sum awk date; do
  if ! command -v "$tool" &>/dev/null; then
    echo "ERROR: required tool '$tool' not found in PATH" >&2
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# Verify rust-toolchain.toml is present (reproducibility requirement)
# ---------------------------------------------------------------------------
if [ ! -f "${REPO_ROOT}/rust-toolchain.toml" ]; then
  echo "ERROR: rust-toolchain.toml not found — pinned toolchain is required for reproducible builds" >&2
  exit 1
fi

TOOLCHAIN_CHANNEL=$(grep 'channel' "${REPO_ROOT}/rust-toolchain.toml" | awk -F'"' '{print $2}')
echo "Rust toolchain: ${TOOLCHAIN_CHANNEL} (from rust-toolchain.toml)"

# ---------------------------------------------------------------------------
# Build all contracts
# ---------------------------------------------------------------------------
echo "Building WASM artifacts (release, wasm32-unknown-unknown)..."
cargo build --release --target wasm32-unknown-unknown \
  --manifest-path "${REPO_ROOT}/Cargo.toml" \
  $(for name in "${!CONTRACTS[@]}"; do echo "-p $name"; done)

# ---------------------------------------------------------------------------
# Compute hashes
# ---------------------------------------------------------------------------
declare -A NEW_HASHES
for name in "${!CONTRACTS[@]}"; do
  wasm_path="${REPO_ROOT}/${CONTRACTS[$name]}"
  if [ ! -f "${wasm_path}" ]; then
    echo "ERROR: WASM artifact not found: ${wasm_path}" >&2
    echo "  Build may have failed or the contract name is wrong." >&2
    exit 1
  fi
  hash=$(sha256sum "${wasm_path}" | awk '{print $1}')
  NEW_HASHES["$name"]="$hash"
  echo "  ${name}: ${hash}"
done

# ---------------------------------------------------------------------------
# Dry-run: print and exit
# ---------------------------------------------------------------------------
if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "--- DRY RUN: checksums.sha256 would be updated to ---"
  for name in "${!NEW_HASHES[@]}"; do
    echo "${NEW_HASHES[$name]}  ${name}.wasm"
  done
  echo "--- No files were modified ---"
  exit 0
fi

# ---------------------------------------------------------------------------
# Write checksums file
# ---------------------------------------------------------------------------
TODAY=$(date -u +%Y-%m-%d)

{
  cat <<EOF
# Fluxora Contract WASM Checksums
#
# Reference SHA256 checksums for reproducible WASM builds.
# CI verifies that a fresh build produces byte-identical artifacts.
#
# Format: <sha256>  <filename>
# Generated by: script/update-wasm-checksums.sh
# Last updated: ${TODAY}
# Rust toolchain: ${TOOLCHAIN_CHANNEL}
#
# To regenerate: bash script/update-wasm-checksums.sh
# To verify:     bash script/verify-wasm-checksum.sh
#
# Determinism contract:
#   - Rust toolchain pinned via rust-toolchain.toml
#   - soroban-sdk version pinned in each contract's Cargo.toml
#   - Build uses --release with wasm32-unknown-unknown target
#   - No environment-dependent flags beyond the pinned toolchain
#
EOF
  for name in "${!NEW_HASHES[@]}"; do
    echo "${NEW_HASHES[$name]}  ${name}.wasm"
  done
} > "${CHECKSUMS_FILE}"

echo ""
echo "Updated ${CHECKSUMS_FILE}"
echo "Commit this file alongside your source changes."
echo ""
echo "To verify the build is reproducible, run:"
echo "  bash script/verify-wasm-checksum.sh"
